"""schema initial

Revision ID: 2c2c05599f46
Revises: 
Create Date: 2026-06-12 14:00:28.913196

"""
from alembic import op
import sqlalchemy as sa


revision = '2c2c05599f46'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('campaigns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('grid_id', sa.String(length=80), nullable=False),
    sa.Column('institution_id', sa.String(length=80), nullable=False),
    sa.Column('campaign_date', sa.Date(), nullable=False),
    sa.Column('window_reference', sa.String(length=20), nullable=False),
    sa.Column('date_ouverture', sa.DateTime(timezone=True), nullable=True),
    sa.Column('date_cloture', sa.DateTime(timezone=True), nullable=True),
    sa.Column('statut', sa.String(length=20), nullable=False),
    sa.Column('frozen_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("statut IN ('ouverte', 'cloturee', 'gelee')", name='ck_campaign_statut'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('nom', sa.String(length=120), nullable=False),
    sa.Column('prenom', sa.String(length=120), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('actif', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("role IN ('enseignant', 'commission', 'admin')", name='ck_user_role'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('benefits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('platform_close_date', sa.Date(), nullable=True),
    sa.Column('source', sa.String(length=40), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dossiers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('candidate_ref', sa.String(length=40), nullable=False),
    sa.Column('population', sa.String(length=60), nullable=False),
    sa.Column('departement', sa.String(length=80), nullable=True),
    sa.Column('pays', sa.String(length=80), nullable=True),
    sa.Column('duree_jours', sa.Integer(), nullable=True),
    sa.Column('billet_estime_da', sa.Float(), nullable=True),
    sa.Column('frais_divers_da', sa.Float(), nullable=True),
    sa.Column('statut', sa.String(length=20), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("statut IN ('brouillon', 'soumis', 'gele')", name='ck_dossier_statut'),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('campaign_id', 'user_id', name='uq_dossier_campaign_user')
    )
    op.create_table('ranking_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dossier_id', sa.Integer(), nullable=False),
    sa.Column('criterion_id', sa.String(length=80), nullable=False),
    sa.Column('item_id', sa.String(length=80), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('date_activite', sa.Date(), nullable=True),
    sa.Column('statut', sa.String(length=20), nullable=False),
    sa.Column('decision_motif', sa.Text(), nullable=True),
    sa.Column('decided_by', sa.Integer(), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("statut <> 'rejete' OR decision_motif IS NOT NULL", name='ck_entry_rejet_motive'),
    sa.CheckConstraint("statut IN ('en_attente', 'valide', 'rejete')", name='ck_entry_statut'),
    sa.ForeignKeyConstraint(['decided_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['dossier_id'], ['dossiers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dossier_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=60), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['dossier_id'], ['dossiers.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('attachments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entry_id', sa.Integer(), nullable=False),
    sa.Column('dossier_id', sa.Integer(), nullable=False),
    sa.Column('filename_original', sa.String(length=255), nullable=False),
    sa.Column('stored_path', sa.String(length=500), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('content_type', sa.String(length=100), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['dossier_id'], ['dossiers.id'], ),
    sa.ForeignKeyConstraint(['entry_id'], ['entries.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('entry_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('attachments')
    op.drop_table('events')
    op.drop_table('entries')
    op.drop_table('ranking_snapshots')
    op.drop_table('dossiers')
    op.drop_table('benefits')
    op.drop_table('users')
    op.drop_table('campaigns')
    # ### end Alembic commands ###
